name: Cleanup Vercel Preview Deployments

description: "Manually destroy Vercel preview deployments."

on:
  workflow_dispatch:

jobs:
  destroy-vercel-deployment:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Remove Vercel deployment
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel remove firebase-vercel --safe --yes --token $VERCEL_TOKEN
